name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      nodever:
        description: 'Version de node'
        type: choice
        required: true
        options:
          - '18'
          - '17'
          - '16'
          - '15'
          - '14'
          - '13'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ alpine ]
        include:
          - os: alpine
            tag_latest_on: 18  # This value is add only when we are in job alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAGS="${GITHUB_REPOSITORY}:${{ github.event.inputs.nodever }}-${{ matrix.os }}"
          if [[ "${{ github.event.inputs.nodever }}" == "${{ matrix.tag_latest_on }}" ]]; then
            TAGS="${TAGS},${GITHUB_REPOSITORY}:latest"
          fi
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ github.event.inputs.nodever }}/${{ matrix.os }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
